### ISSUE TITLE
重啟後園藝玻璃罩內的植物消失

### ISSUE THREAD

**Issue by HeyNight0712** [SlimefunGuguProject/Cultivation#19]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Cultivation/issues)，且没有找到相同的问题

### 问题描述

當重啟伺服器後 園藝玻璃罩 內的植物會全部消失

![image](https://github.com/SlimefunGuguProject/Cultivation/assets/97263430/22d0b2fc-6781-487f-a259-de133cdeeabd)

### 复现步骤

放置好 園藝玻璃罩 並且 放置植物 重啟伺服器後 裡面內的植物全數消失
![image](https://github.com/SlimefunGuguProject/Cultivation/assets/97263430/2a74d31c-1d69-4b4b-8492-c13b26b77179)

### 预期行为

似乎是讀黨 沒有整個讀進去 而且一直在後台跑出此問題
![image](https://github.com/SlimefunGuguProject/Cultivation/assets/97263430/8c7d841e-e7b9-4b4a-934e-64ad1271ab28)

### 服务端软件

Paper

### Minecraft 版本

1.19.4

### Slimefun版本

![image](https://github.com/SlimefunGuguProject/Cultivation/assets/97263430/23163441-ce33-4051-8fe5-ea00998bc364)

### 插件版本

6102f08

**Comment by ybw0014** [comment]
已修复
