### ISSUE TITLE
Cultivation 无限刷WARN警告 报错

### ISSUE THREAD

**Issue by MoeShimaKaze** [SlimefunGuguProject/Cultivation#21]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Cultivation/issues)，且没有找到相同的问题

### 问题描述

在更新粘液科技版本（从2023.02更新到2023.06）和农耕工艺版本（从Build 1更新到Build 4）后，玩家进入服务器后，只要身边有农耕工艺的物品就会在服务器后台无限刷出此警告报错

### 复现步骤

1.启动服务器后并完成粘液科技的数据迁移
2.玩家进入服务器
3.玩家身旁有农耕工艺的物品就会报错

### 预期行为

理论上数据正常迁移应该不会有问题才是

### 服务器日志

https://paste.fastmirror.net/?7dc40e33ec70e5ac#Fe27WBHkZZfwdLv7DSxS9Euf8MWooUPhButafN4Aczd2

### 错误报告

https://paste.fastmirror.net/?7dc40e33ec70e5ac#Fe27WBHkZZfwdLv7DSxS9Euf8MWooUPhButafN4Aczd2

### 服务端软件

Purpur

### Minecraft 版本

git-Purpur-1985 (MC: 1.19.4)

### Slimefun版本

Slimefun v2023.06-release

### 插件版本

4

**Comment by ybw0014** [comment]
尝试使用金丝雀版本 https://builds.guizhanss.com/StarWishsama/Slimefun4/master

**Comment by MoeShimaKaze** [comment]
> 尝试使用金丝雀版本 https://builds.guizhanss.com/StarWishsama/Slimefun4/master

我使用金丝雀版本时，旧版本的方块数据无法导入至金丝雀版本中

**Comment by MoeShimaKaze** [comment]
测试步骤：
先从2023.02版本的粘液科技将数据导入至2023.06中，数据可以成功导入，此时Cultivation的版本 仍然是Build 1
再将粘液的版本换成金丝雀版本，并将Cultivation的版本升级为Build 4，服务器可正常开启
但是一进入服务器之后，周围有Cultivation的物品就开始疯狂刷出上述报错
问题仍未得到解决
