### ISSUE TITLE
"CLT_PLANT_DARKNESS"

### ISSUE THREAD

**Issue by guduxof** [SlimefunGuguProject/Cultivation#26]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Cultivation/issues)，且没有找到相同的问题

### 问题描述

 Item "CLT_PLANT_DARKNESS" from Cultivation vBuild 10 (git fda0c09) has caused an Error! 导致错误 
修复完了 记得给我发送邮件 告知我使用最新版 3445197953@qq.com

### 复现步骤

 Item "CLT_PLANT_DARKNESS" from Cultivation vBuild 10 (git fda0c09) has caused an Error

### 预期行为

 Item "CLT_PLANT_DARKNESS" from Cultivation vBuild 10 (git fda0c09) has caused an Error!

### 服务端软件

Paper

### Minecraft 版本

1.20.4

### Slimefun版本

paper git-paper-497 (mc: 1.20.4)
slimpfun 2024.04-release
metrics-组件 #29
java 21

### 插件版本

10

**Comment by ybw0014** [comment]
duplicate of #23
