### ISSUE TITLE
无法加载插件

### ISSUE THREAD

**Issue by hseermc** [SlimefunGuguProject/Cultivation#29]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Cultivation/issues)，且没有找到相同的问题

### 问题描述

在服务器启动时无法加载插件(is it up to date?)
服务端：1.20.4 leaves

### 复现步骤

1.下载最新版插件
2.开机
3.就自动禁用不能用了

### 预期行为

能正常启动

### 错误报告

https://paste.guizhanss.net/lXvYp

### 服务端软件

其他 (请在问题描述里写明)

### Minecraft 版本

1.20.4

### Slimefun版本

Slimefun v4390b5e-Insider

### 插件版本

11

**Comment by ybw0014** [comment]
ed9a7f3
